{% set name = "gillespy2" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f5267b3ccac8d5380dbd10b31171bdb9e75b9d633c1ea6a6cccefdad1010a3f1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
requirements:
  host:
    - python >3.5
    - pip
    - setuptools >=41.0.1

  run:
    - python >3.5
    - matplotlib-base >=3.0.3
    - plotly >=4.1.0
    - scipy >=1.3.1

test:
  imports:
    - gillespy2

about:
  home: https://github.com/GillesPy2/GillesPy2
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: GillesPy2 is an open-source Python package for stochastic simulation of biochemical systems.

  description: |
    GillesPy2 is an open-source Python package for stochastic simulation of biochemical systems. 
    It offers an object-oriented approach for creating mathematical models of biological systems, 
    as well as a variety of methods for performing time simulation of those models.

  doc_url: https://gillespy2.readthedocs.io/en/latest/
  dev_url: https://github.com/GillesPy2/GillesPy2

extra:
  recipe-maintainers:
    - briandrawert
    - Fin109
    - seanebum
